version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"

  flask:
    build: .
    container_name: flask_container
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: testuser
      DATABASE_PASSWORD: testpass
      DATABASE_NAME: testdb
